name: Test Build

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: {}

jobs:
  build-test-kernels:
    name: "Test Build ${{ matrix.kernel_version }}.${{ matrix.sub_level }}-${{ matrix.android_version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          # # Android 14 - 6.1 oldest (OLD)
          # - android_version: "android14"
          #   kernel_version: "6.1"
          #   sub_level: "25"
          #   os_patch_level: "2023-06"
          
          # Android 14 - 6.1 LTS (NEW)
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "X"
            os_patch_level: "lts"
          
          # Android 14 - 6.1 specific sublevel (OLD)
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "134"
            os_patch_level: "2025-05"
          
          # Android 15 - 6.6 oldest (NEW)
          - android_version: "android15"
            kernel_version: "6.6"
            sub_level: "30"
            os_patch_level: "2024-07"
          
          # Android 15 - 6.6 LTS (OLD)
          - android_version: "android15"
            kernel_version: "6.6"
            sub_level: "X"
            os_patch_level: "lts"
    
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
